"""
VoltGuard Reports UI
----------------------
Displays security alerts with acknowledge/export functionality.
Supports PDF and CSV export via reportlab and the standard csv module.
"""

from __future__ import annotations

import csv
import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QFileDialog,
    QFrame,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QPushButton,
    QTableWidget,
    QTableWidgetItem,
    QVBoxLayout,
    QWidget,
    QMessageBox,
)

from database.database import get_db
from core.logger import get_logger

log = get_logger(__name__)

EXPORTS_DIR = Path(__file__).resolve().parent.parent / "exports"


class ReportsPage(QWidget):
    """Reports page listing security alerts with acknowledge and export actions."""

    def __init__(self, parent: Optional[QWidget] = None) -> None:
        super().__init__(parent)
        self._db = get_db()
        EXPORTS_DIR.mkdir(parents=True, exist_ok=True)
        self._setup_ui()
        self._load_alerts()

    # ------------------------------------------------------------------
    # UI
    # ------------------------------------------------------------------

    def _setup_ui(self) -> None:
        layout = QVBoxLayout(self)
        layout.setContentsMargins(28, 24, 28, 24)
        layout.setSpacing(16)

        # Header
        header = QHBoxLayout()
        title = QLabel("Reports & Alerts")
        title.setObjectName("PageTitle")
        header.addWidget(title)
        header.addStretch()

        self._ack_btn = QPushButton("✓  Acknowledge Selected")
        self._ack_btn.setObjectName("SecondaryButton")
        self._ack_btn.clicked.connect(self._acknowledge_selected)

        self._export_csv_btn = QPushButton("↓  Export CSV")
        self._export_csv_btn.setObjectName("SecondaryButton")
        self._export_csv_btn.clicked.connect(self._export_csv)

        self._export_pdf_btn = QPushButton("↓  Export PDF")
        self._export_pdf_btn.setObjectName("SecondaryButton")
        self._export_pdf_btn.clicked.connect(self._export_pdf)

        self._refresh_btn = QPushButton("↻  Refresh")
        self._refresh_btn.setObjectName("PrimaryButton")
        self._refresh_btn.clicked.connect(self._load_alerts)

        for btn in (
            self._ack_btn,
            self._export_csv_btn,
            self._export_pdf_btn,
            self._refresh_btn,
        ):
            header.addWidget(btn)

        layout.addLayout(header)

        desc = QLabel(
            "Security alerts generated by the decision engine. "
            "Select rows and click 'Acknowledge' to mark them as reviewed."
        )
        desc.setObjectName("SmallMuted")
        desc.setWordWrap(True)
        layout.addWidget(desc)

        # Alert summary row
        summary_row = QHBoxLayout()
        summary_row.setSpacing(14)
        self._total_label = _badge("Total Alerts", "0", "#00D4FF")
        self._unack_label = _badge("Unacknowledged", "0", "#EF4444")
        self._critical_label = _badge("Critical", "0", "#F97316")
        for badge in (self._total_label, self._unack_label, self._critical_label):
            summary_row.addWidget(badge)
        summary_row.addStretch()
        layout.addLayout(summary_row)

        # Alerts table
        self._table = QTableWidget(0, 7)
        self._table.setObjectName("PacketTable")
        self._table.setHorizontalHeaderLabels(
            ["ID", "Timestamp", "Event Type", "Severity", "Source IP", "Destination IP", "Description"]
        )
        self._table.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self._table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeToContents)
        self._table.verticalHeader().setVisible(False)
        self._table.setEditTriggers(QTableWidget.NoEditTriggers)
        self._table.setSelectionBehavior(QTableWidget.SelectRows)
        self._table.setAlternatingRowColors(True)

        layout.addWidget(self._table)

    # ------------------------------------------------------------------
    # Data loading
    # ------------------------------------------------------------------

    def _load_alerts(self) -> None:
        """Reload the alerts table from the database."""
        alerts = self._db.get_recent_alerts(limit=500)
        self._table.setRowCount(0)

        total = len(alerts)
        unack = sum(1 for a in alerts if not a["acknowledged"])
        critical = sum(1 for a in alerts if a["severity"] == "CRITICAL")

        # Update badges
        _set_badge_value(self._total_label, str(total))
        _set_badge_value(self._unack_label, str(unack))
        _set_badge_value(self._critical_label, str(critical))

        severity_colors = {
            "CRITICAL": "#EF4444",
            "HIGH": "#F97316",
            "MEDIUM": "#F59E0B",
            "LOW": "#00E676",
            "INFO": "#00D4FF",
        }

        for alert in alerts:
            row = self._table.rowCount()
            self._table.insertRow(row)
            cells = [
                str(alert["id"]),
                str(alert["timestamp"] or ""),
                str(alert["event_type"] or ""),
                str(alert["severity"] or ""),
                str(alert["src_ip"] or "—"),
                str(alert["dst_ip"] or "—"),
                str(alert["description"] or ""),
            ]
            for col, text in enumerate(cells):
                item = QTableWidgetItem(text)
                item.setTextAlignment(Qt.AlignVCenter | Qt.AlignLeft)
                if col == 3:  # severity
                    from PySide6.QtGui import QColor
                    color = severity_colors.get(text, "#E2E8F0")
                    item.setForeground(QColor(color))
                # Dim acknowledged rows
                if alert["acknowledged"]:
                    from PySide6.QtGui import QColor
                    item.setForeground(QColor("#4B5563"))
                self._table.setItem(row, col, item)

    # ------------------------------------------------------------------
    # Actions
    # ------------------------------------------------------------------

    def _acknowledge_selected(self) -> None:
        """Acknowledge all currently selected alert rows."""
        selected_rows = set(idx.row() for idx in self._table.selectedIndexes())
        if not selected_rows:
            QMessageBox.information(self, "Nothing Selected", "Please select at least one alert row.")
            return

        for row in selected_rows:
            id_item = self._table.item(row, 0)
            if id_item:
                try:
                    alert_id = int(id_item.text())
                    self._db.acknowledge_alert(alert_id)
                except ValueError:
                    pass

        self._load_alerts()
        log.info("Acknowledged %d alerts.", len(selected_rows))

    def _export_csv(self) -> None:
        """Export all visible alerts to a CSV file."""
        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        default_path = str(EXPORTS_DIR / f"voltguard_alerts_{timestamp}.csv")

        path, _ = QFileDialog.getSaveFileName(
            self, "Export Alerts as CSV", default_path, "CSV Files (*.csv)"
        )
        if not path:
            return

        alerts = self._db.get_recent_alerts(limit=10000)
        try:
            with open(path, "w", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                writer.writerow(
                    ["ID", "Timestamp", "Event Type", "Severity", "Source IP", "Destination IP", "Description", "Acknowledged"]
                )
                for alert in alerts:
                    writer.writerow([
                        alert["id"],
                        alert["timestamp"],
                        alert["event_type"],
                        alert["severity"],
                        alert["src_ip"],
                        alert["dst_ip"],
                        alert["description"],
                        "Yes" if alert["acknowledged"] else "No",
                    ])
            QMessageBox.information(self, "Export Complete", f"Alerts exported to:\n{path}")
            log.info("Alerts exported to CSV: %s", path)
        except Exception as exc:
            QMessageBox.critical(self, "Export Failed", str(exc))
            log.error("CSV export failed: %s", exc)

    def _export_pdf(self) -> None:
        """Export all visible alerts to a PDF report using ReportLab."""
        try:
            from reportlab.lib.pagesizes import A4, landscape
            from reportlab.lib import colors
            from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
            from reportlab.lib.styles import getSampleStyleSheet
        except ImportError:
            QMessageBox.warning(self, "ReportLab Missing", "Install reportlab to enable PDF export.")
            return

        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        default_path = str(EXPORTS_DIR / f"voltguard_report_{timestamp}.pdf")

        path, _ = QFileDialog.getSaveFileName(
            self, "Export Report as PDF", default_path, "PDF Files (*.pdf)"
        )
        if not path:
            return

        alerts = self._db.get_recent_alerts(limit=10000)

        try:
            doc = SimpleDocTemplate(path, pagesize=landscape(A4))
            styles = getSampleStyleSheet()
            elements = []

            elements.append(Paragraph("VoltGuard IDS — Security Alert Report", styles["Title"]))
            elements.append(Paragraph(
                f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC | Total Alerts: {len(alerts)}",
                styles["Normal"],
            ))
            elements.append(Spacer(1, 12))

            data = [["ID", "Timestamp", "Event Type", "Severity", "Source IP", "Destination IP", "Acknowledged"]]
            for alert in alerts:
                data.append([
                    str(alert["id"]),
                    str(alert["timestamp"] or ""),
                    str(alert["event_type"] or ""),
                    str(alert["severity"] or ""),
                    str(alert["src_ip"] or "—"),
                    str(alert["dst_ip"] or "—"),
                    "Yes" if alert["acknowledged"] else "No",
                ])

            table = Table(data, repeatRows=1)
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1A1F2E")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#00D4FF")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#0D1117"), colors.HexColor("#161B27")]),
                ("TEXTCOLOR", (0, 1), (-1, -1), colors.HexColor("#E2E8F0")),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#2D3748")),
                ("PADDING", (0, 0), (-1, -1), 4),
            ]))
            elements.append(table)
            doc.build(elements)

            QMessageBox.information(self, "Export Complete", f"PDF report saved to:\n{path}")
            log.info("Alerts exported to PDF: %s", path)
        except Exception as exc:
            QMessageBox.critical(self, "Export Failed", str(exc))
            log.error("PDF export failed: %s", exc)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _badge(title: str, value: str, color: str) -> QFrame:
    """Create a small summary badge widget."""
    frame = QFrame()
    frame.setObjectName("StatCard")
    frame.setFixedHeight(70)
    frame.setFixedWidth(160)
    layout = QVBoxLayout(frame)
    layout.setContentsMargins(12, 8, 12, 8)
    layout.setSpacing(2)
    t = QLabel(title)
    t.setObjectName("StatCardTitle")
    v = QLabel(value)
    v.setObjectName("BadgeValue")
    v.setStyleSheet(f"color: {color}; font-size: 22px; font-weight: 700;")
    v.setObjectName(f"badge_value_{title.replace(' ', '_')}")
    layout.addWidget(t)
    layout.addWidget(v)
    return frame


def _set_badge_value(badge: QFrame, value: str) -> None:
    """Update the value label inside a badge frame."""
    for child in badge.findChildren(QLabel):
        if child.objectName().startswith("badge_value_"):
            child.setText(value)
            break
